name = "note-tagger"
main = "build/index.js"
compatibility_date = "2025-11-19"

[observability]
enabled = true

[build]
command = "cargo leptos build --release --bin-features 'ssr cloudflare' && worker-build --release -- --features ssr,cloudflare && cp target/site/pkg/note-tagger.wasm target/site/pkg/note-tagger_bg.wasm"

[assets]
directory = "./target/site"

[[r2_buckets]]
binding     = "note-tagger-bucket"
bucket_name = "note-tagger-stg"
